const sent = `If you're visiting this page, you're likely here because you're searching for a random sentence. Sometimes a random word just isn't enough, and that is where the random sentence generator comes into play. By inputting the desired number, you can make a list of as many random sentences as you want or need. Producing random sentences can be helpful in a number of different ways.

For writers, a random sentence can help them get their creative juices flowing. Since the topic of the sentence is completely unknown, it forces the writer to be creative when the sentence appears. There are a number of different ways a writer can use the random sentence for creativity. The most common way to use the sentence is to begin a story. Another option is to include it somewhere in the story. A much more difficult challenge is to use it to end a story. In any of these cases, it forces the writer to think creatively since they have no idea what sentence will appear from the tool.

For those writers who have writers' block, this can be an excellent way to take a step to crumbling those walls. By taking the writer away from the subject matter that is causing the block, a random sentence may allow them to see the project they're working on in a different light and perspective. Sometimes all it takes is to get that first sentence down to help break the block.

It can also be successfully used as a daily exercise to get writers to begin writing. Being shown a random sentence and using it to complete a paragraph each day can be an excellent way to begin any writing session.

Random sentences can also spur creativity in other types of projects being done. If you are trying to come up with a new concept, a new idea or a new product, a random sentence may help you find unique qualities you may not have considered. Trying to incorporate the sentence into your project can help you look at it in different and unexpected ways than you would normally on your own.

It can also be a fun way to surprise others. You might choose to share a random sentence on social media just to see what type of reaction it garners from others. It's an unexpected move that might create more conversation than a typical post or tweet.

These are just a few ways that one might use the random sentence generator for their benefit. If you're not sure if it will help in the way you want, the best course of action is to try it and see. Have several random sentences generated and you'll soon be able to see if they can help with your project.

Our goal is to make this tool as useful as possible. For anyone who uses this tool and comes up with a way we can improve it, we'd love to know your thoughts. Please contact us so we can consider adding your ideas to make the random sentence generator the best it can be.`;

const s = sent.split(",");

const fn = [
	"Adam",
	"Alex",
	"Aaron",
	"Ben",
	"Carl",
	"Dan",
	"David",
	"Edward",
	"Fred",
	"Frank",
	"George",
	"Hal",
	"Hank",
	"Ike",
	"John",
	"Jack",
	"Joe",
	"Larry",
	"Monte",
	"Matthew",
	"Mark",
	"Nathan",
	"Otto",
	"Paul",
	"Peter",
	"Roger",
	"Roger",
	"Steve",
	"Thomas",
	"Tim",
	"Ty",
	"Victor",
	"Walter",
];

const ln = [
	"Anderson",
	"Ashwoon",
	"Aikin",
	"Bateman",
	"Bongard",
	"Bowers",
	"Boyd",
	"Cannon",
	"Cast",
	"Deitz",
	"Dewalt",
	"Ebner",
	"Frick",
	"Hancock",
	"Haworth",
	"Hesch",
	"Hoffman",
	"Kassing",
	"Knutson",
	"Lawless",
	"Lawicki",
	"Mccord",
	"McCormack",
	"Miller",
	"Myers",
	"Nugent",
	"Ortiz",
	"Orwig",
	"Ory",
	"Paiser",
	"Pak",
	"Pettigrew",
	"Quinn",
	"Quizoz",
	"Ramachandran",
	"Resnick",
	"Sagar",
	"Schickowski",
	"Schiebel",
	"Sellon",
	"Severson",
	"Shaffer",
	"Solberg",
	"Soloman",
	"Sonderling",
	"Soukup",
	"Soulis",
	"Stahl",
	"Sweeney",
	"Tandy",
	"Trebil",
	"Trusela",
	"Trussel",
	"Turco",
	"Uddin",
	"Uflan",
	"Ulrich",
	"Upson",
	"Vader",
	"Vail",
	"Valente",
	"Van Zandt",
	"Vanderpoel",
	"Ventotla",
	"Vogal",
	"Wagle",
	"Wagner",
	"Wakefield",
	"Weinstein",
	"Weiss",
	"Woo",
	"Yang",
	"Yates",
	"Yocum",
	"Zeaser",
	"Zeller",
	"Ziegler",
	"Bauer",
	"Baxster",
	"Casal",
	"Cataldi",
	"Caswell",
	"Celedon",
	"Chambers",
	"Chapman",
	"Christensen",
	"Darnell",
	"Davidson",
	"Davis",
	"DeLorenzo",
	"Dinkins",
	"Doran",
	"Dugelman",
	"Dugan",
	"Duffman",
	"Eastman",
	"Ferro",
	"Ferry",
	"Fletcher",
	"Fietzer",
	"Hylan",
	"Hydinger",
	"Illingsworth",
	"Ingram",
	"Irwin",
	"Jagtap",
	"Jenson",
	"Johnson",
	"Johnsen",
	"Jones",
	"Jurgenson",
	"Kalleg",
	"Kaskel",
	"Keller",
	"Leisinger",
	"LePage",
	"Lewis",
	"Linde",
	"Lulloff",
	"Maki",
	"Martin",
	"McGinnis",
	"Mills",
	"Moody",
	"Moore",
	"Napier",
	"Nelson",
	"Norquist",
	"Nuttle",
	"Olson",
	"Ostrander",
	"Reamer",
	"Reardon",
	"Reyes",
	"Rice",
	"Ripka",
	"Roberts",
	"Rogers",
	"Root",
	"Sandstrom",
	"Sawyer",
	"Schlicht",
	"Schmitt",
	"Schwager",
	"Schutz",
	"Schuster",
	"Tapia",
	"Thompson",
	"Tiernan",
	"Tisler",
];

const c = [
	"Did you have a nice summer?",
	"I wonder what happened.",
	"It is raining worse than ever.",
	"The hotel is down there.",
	"I am not certain about that.",
	"My father must do the work.",
	"I'll have exams right after the summer holidays.",
	"I'm taking my son to the zoo this afternoon.",
	"Keep your eyes open.",
	"We are acquainted with his family.",
	"Your collar has a stain on it.",
	"Have you eaten?",
	"My mother is making a cake for my father.",
	"Where can I pick up my baggage?",
	"Would you like bacon or sausage?",
	"Do you think you might have left it there?",
	"What are their names?",
	"I'll pay for dinner.",
	"My sister became a college student.",
	"I hear that his father is in another country.",
	"She ignored him all day.",
	"I don't remember seeing you two years ago.",
	"She went for a walk with him this morning.",
	"She advised him where to stay.",
	"How old do you think I am?",
	"Outside the hotel.",
	"How about the one after that?",
	"Please refer to paragraph ten.",
	"He's shorter than Tom.",
	"Bob was very happy.",
];

const names = document.querySelectorAll(".os-win .zoWT4");

const messages = document.querySelectorAll(".Nm1g1 span.i0jNr span");

function rnd(arr) {
	return Math.round(Math.round(Math.random() * arr.length));
}
